/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
    light: {
        text: '#11181C',
        background: '#fff',
        tint: tintColorLight,
        icon: '#687076',
        tabIconDefault: '#687076',
        tabIconSelected: tintColorLight,
        // Colori aggiuntivi per l'UI
        border: '#e1e1e1',
        card: '#f8f9fa',
        placeholder: '#666',
        muted: '#f0f0f0',
        accent: '#e3f2fd',
        primary: '#007AFF',
        danger: '#ff3b30',
        success: '#00FF00',
        warning: '#FF6600',
        shadow: '#000',
        // Colori per pulsanti floating
        locationButton: 'rgba(0, 122, 255, 0.9)',
        locationButtonActive: 'rgba(0, 122, 255, 1)',
        elevationButton: 'rgba(34, 197, 94, 0.9)',
        elevationButtonActive: 'rgba(34, 197, 94, 1)',
        trackButton: 'rgba(168, 85, 247, 0.9)',
        trackButtonActive: 'rgba(168, 85, 247, 1)',
        buttonText: '#fff',
        modalBackground: '#fff',
        modalText: '#374151',
        modalTrack: '#F3F4F6',
        // Colori per waypoint
        waypointStart: '#00FF00',
        waypointFinish: '#FF0000',
        waypointSummit: '#8B4513',
        waypointWater: '#0066FF',
        waypointCamp: '#8B4513',
        waypointRestaurant: '#FF6600',
        waypointDanger: '#FF0000',
        waypointViewpoint: '#9900FF',
        waypointBridge: '#666666',
        waypointChurch: '#8B4513',
        waypointDefault: '#007AFF',
        // Colori per track selector
        trackSelectorBorder: '#E5E7EB',
        trackSelectorActiveBackground: '#DBEAFE',
        trackSelectorActiveBorder: '#3B82F6',
        trackSelectorText: '#6B7280',
        trackSelectorActiveText: '#1E40AF',
    },
    dark: {
        text: '#ECEDEE',
        background: '#151718',
        tint: tintColorDark,
        icon: '#9BA1A6',
        tabIconDefault: '#9BA1A6',
        tabIconSelected: tintColorDark,
        // Colori aggiuntivi per l'UI
        border: '#333',
        card: '#1f2937',
        placeholder: '#9BA1A6',
        muted: '#374151',
        accent: '#1e3a8a',
        primary: '#60A5FA',
        danger: '#EF4444',
        success: '#10B981',
        warning: '#F59E0B',
        shadow: '#000',
        // Colori per pulsanti floating
        locationButton: 'rgba(100, 149, 237, 0.9)',
        locationButtonActive: 'rgba(100, 149, 237, 1)',
        elevationButton: 'rgba(72, 187, 120, 0.9)',
        elevationButtonActive: 'rgba(72, 187, 120, 1)',
        trackButton: 'rgba(139, 92, 246, 0.9)',
        trackButtonActive: 'rgba(139, 92, 246, 1)',
        buttonText: '#fff',
        modalBackground: '#1f2937',
        modalText: '#ECEDEE',
        modalTrack: '#374151',
        // Colori per waypoint (versioni dark-mode friendly)
        waypointStart: '#4ADE80',
        waypointFinish: '#F87171',
        waypointSummit: '#D2691E',
        waypointWater: '#60A5FA',
        waypointCamp: '#D2691E',
        waypointRestaurant: '#FB923C',
        waypointDanger: '#F87171',
        waypointViewpoint: '#C084FC',
        waypointBridge: '#9CA3AF',
        waypointChurch: '#D2691E',
        waypointDefault: '#60A5FA',
        // Colori per track selector (dark mode)
        trackSelectorBorder: '#374151',
        trackSelectorActiveBackground: '#1e3a8a',
        trackSelectorActiveBorder: '#60A5FA',
        trackSelectorText: '#9CA3AF',
        trackSelectorActiveText: '#DBEAFE',
    },
};
